import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :juaBado, JuaBadoWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json",
force_ssl: [rewrite_on: [:x_forwarded_proto]]
# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: JuaBado.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :my_app, MyApp.Repo,
  adapter: Ecto.Adapters.Postgres, # Or whichever adapter you're using
  username: System.fetch_env!("ca8405f3-8d95-4dd3-9461-53e8e9fcefd3-user"),
  password: System.fetch_env!("pw-dcb74bbd-f6a8-4e5f-b744-c7e1120b68b1"),
  database: System.fetch_env!("ca8405f3-8d95-4dd3-9461-53e8e9fcefd3"),
  hostname: System.fetch_env!("postgres-free-tier-v2020.gigalixir.com"),
  pool_size: String.to_integer(System.fetch_env!("POOL_SIZE") || "10"),
  ssl: false # Disable SSL
